openapi: 3.0.0
info:
  title: Chat API
  description: API specification for the Chat backend
  version: 1.0.0
servers:
  - url: https://api.smalltech.in
    description: Production server running on Google Cloud Platform (GCP)

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns a hello world message to verify the service is up.
      responses:
        "200":
          description: Successful health check
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World

  /chat:
    post:
      summary: Chat with the bot
      description: Send a user message and receive a chatbot response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: string
                  description: The user’s message
                  example: "Hello bot"
                session_id:
                  type: string
                  description: Session identifier for maintaining context. **Must be a valid UUID.**
                  example: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                request_type:
                  type: string
                  description: The type of the query/agent required
                  example: "sales"
      responses:
        "200":
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  response:
                    type: string
                    description: Bot response message
                    example: "Hi there! How can I help you today?"
        "400":
          description: Invalid input error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Input cannot be empty."
        "500":
          description: Server error during LLM call
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Sorry, something went wrong while processing your message. Please try again later."
  /history:
    get:
      summary: Get or create chat history
      description: >
        Returns the chat history for the given `session_id`.  
        If the session does not exist, a new one is created and initialized with the first AI message.
      parameters:
        - name: session_id
          in: query
          required: true
          schema:
            type: string
          description: Unique session identifier
      responses:
        '200':
          description: Chat history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [human, ai]
                          description: Sender of the message
                        content:
                          type: string
                          description: Message text
                example:
                  history:
                    - type: human
                      content: "Hello"
                    - type: ai
                      content: "Hi there! How can I help you?"
        '201':
          description: New chat session created with first AI message
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    description: Newly created session identifier
                  history:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [human, ai]
                          description: Sender of the message
                        content:
                          type: string
                          description: Message text
                example:
                  session_id: "xyz789"
                  history:
                    - type: ai
                      content: "Hello! I’m your assistant. How can I help you today?"
        '400':
          description: Invalid session_id format
        '500':
          description: Server error
  /leads:
    get:
      summary: Retrieve stored chat info
      description: >
        Fetch all chat info records stored in the database.  
        Each record contains session details such as name, email, and mobile number.
      responses:
        "200":
          description: Successfully retrieved chat info
          content:
            application/json:
              schema:
                type: object
                properties:
                  chat_info:
                    type: array
                    items:
                      type: object
                      properties:
                        session_id:
                          type: string
                          description: Session identifier
                          example: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                        name:
                          type: string
                          description: Name of the user
                          example: "Vivek Agarwal"
                        email:
                          type: string
                          format: email
                          description: User's email address
                          example: "vivek@example.com"
                        mobile_number:
                          type: string
                          description: User's mobile phone number
                          example: "+91-9876543210"
                        country:
                          type: string
                          description: User's country
                          example: "India"
                        status:
                          type: string
                          enum: [OPEN, CLOSED, QUALIFYING]
                          description: Analyst status for that session id
                          example: "OPEN"
                        remarks:
                          type: string
                          description: Analyst's remark for that session id
                          example: "Send a mail and waiting for a review"
        "500":
          description: Server error while fetching chat info
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unable to fetch chat info. Please try again later."

  /chat-info:
    patch:
      summary: Update lead status and remarks
      description: >
        Update the `status` and/or `remarks` of a lead identified by its `session_id`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
              properties:
                session_id:
                  type: string
                  description: Unique session identifier of the lead
                  example: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                status:
                  type: string
                  description: Updated status of the lead
                  enum: [OPEN, IN_PROGRESS, CLOSED, FOLLOW_UP]
                remarks:
                  type: string
                  description: Analyst's updated remarks
            examples:
              updateStatusOnly:
                summary: Update only status
                value:
                  session_id: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                  status: "CLOSED"
              updateRemarksOnly:
                summary: Update only remarks
                value:
                  session_id: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                  remarks: "Sent follow-up email, awaiting response"
              updateStatusAndRemarks:
                summary: Update both status and remarks
                value:
                  session_id: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                  status: "IN_PROGRESS"
                  remarks: "Client called back, demo scheduled"
      responses:
        "200":
          description: Lead updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Lead updated successfully."
                  updated_lead:
                    type: object
                    properties:
                      session_id:
                        type: string
                        example: "0b3cf7e1-5b30-46df-b018-85ca4dbd4391"
                      status:
                        type: string
                        example: "IN_PROGRESS"
                      remarks:
                        type: string
                        example: "Client called back, demo scheduled"
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid status value provided."
        "404":
          description: Lead not found for the given session_id
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Lead not found."
        "500":
          description: Server error while updating lead
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Unable to update lead. Please try again later."